title: "M E S"
description: "moi's blog."
url: http://rain.moimo.me
baseurl: ""
name: "M E S"
author: "moimo233"
paginate: 8
paginate_path: "/pastdays/page:num/"
kramdown:
  input: GFM
  hard_wrap: true
timezone: Asia/Shanghai
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
future: true
exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor
  - docs
gems:
  - jekyll-feed