title: "M E S"
description: "moi's blog."
url: https://moi-mo.github.io
baseurl: ""
name:"M E S"
author: "moimo233"
paginate: 8
paginate_path: "/blog/page:num/"
kramdown:
  input: GFM
  hard_wrap: true

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor
  - docs
gems:
  - jekyll-feed