head:
   favicon: "https://i.loli.net/2020/03/08/NOLIAjl7qzPp1gw.png" #  the favicon
   high_res_favicon: "https://i.loli.net/2020/03/08/NOLIAjl7qzPp1gw.png" #  the favicon using high quality format
   apple_touch_icon: "https://i.loli.net/2020/03/08/NOLIAjl7qzPp1gw.png" # the iOS Home button icon
   keywords: "moi's blog MES" #  the site keywords

uiux:
   android_chrome_color: "#eeeeee" #  the color of the Chrome address bar
   nprogress_color: "#29d" #  the color of the top loading progress bar
   nprogress_buffer: 200 # the top loading progress bar buffers
   meng: true # meng

background:
   purecolor: "#eeeeee" # the background color

img:
   avatar: "https://i.loli.net/2020/03/08/NOLIAjl7qzPp1gw.png" # your avatar

card:
   card_shadow: 24 # card shadow (0-24), 0 is not displayed
   card_hoverable: false # When the hover to deepen the shadow

many_authors: false

sns_share: # SNS Share Switch
   twitter: true
   facebook: false
   googleplus: false
   weibo: true
   linkedin: false
   qq: true
   telegram: true

comment:
  used: "disqus" # disqus,livere,gitment,valine
  # disqus config
  disqus_shortname: "moimo233" # Your disqus
  disqus_button: false # disqus load button
  disqus_proxy: false # # disqus proxy(Do not use)
  disqus_proxy_url: "" # (Do not use)
  disqus_api_key: "" # (Do not use)
  # livere config
  livere_type: 'city'
  livere_data_uid: ''
  # gitment config
  owner: ""
  repo: ""
  client_id: ""
  client_secret: ""
  #valine config
  valine_notify: false #mail notifier
  valine_verify: false #validation code
  valine_app_id: ''
  valine_app_key: ''
  valine_placeholder: "ヾﾉ≧∀≦)o来啊，快活啊!"

prism:
  themes: prism-solarizedlight
  components:
    - bash
    - cpp
    - python
  plugins:

mathjax: true

google_analytics: "UA-160002693-1"  # google analytics code

baidu_site_verification: ""  # baidu site verification code
google_site_verification: "6jDPZO6YWpbffMtFrp8E16plHz6j4aDjt_j_RiJbf8M"  # google search console verification code

baidu_auto_push: true  # if you used baidu auto push to commit links

lang: ""  # lang

deploy: "" # if you used coding pages

custom_css: "" # Use the assets/css/customCss.css

custom_js: "" # Use the assets/js/customJS.js
